version: '3.8'

services:
  # Database
  postgres:
    build: services/postgres
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - '/opt/volumes/local/postgres/data:/var/lib/postgresql/data:rq'
    env_file:
      - env/postgres.env
    networks:
      - dev-local-network

  # Security
  keycloak:
    build: services/keycloak
    container_name: keycloak
    restart: always
    ports:
      - "8180:8080"
    env_file:
      - env/keycloak.env
    networks:
      - dev-local-network

networks:
  dev-local-network:
    driver: bridge