version: '3.8'

services:
  postgres:
    build: postgres
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - '/opt/volumes/local/postgres/data:/var/lib/postgresql/data:rq'
    env_file:
      - postgres/postgres.env

  mysql:
    build: mysql
    container_name: mysql
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - '/opt/volumes/local/mysql/data:/var/lib/mysql mysql/mysql-server'
    env_file:
      - mysql/mysql.env

  mongodb:
    build: mongo
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - '/opt/volumes/local/dados/mongo/db:/data/db:rq'
    env_file:
      - mongo/mongo.env